FROM nvidia/cuda:12.1.0-cudnn8-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

# system deps
RUN apt-get update && apt-get install -y \
    python3 python3-pip ffmpeg libgl1 \
    && rm -rf /var/lib/apt/lists/*

# python deps
COPY requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r /app/requirements.txt

# code
COPY main.py box_recognition2.py tools.py /app/

# models will be mounted as volume
ENV PYTHONPATH=/app

CMD ["python3", "main.py"]
